server:
  port: 8086
  servlet:
    context-path: '/ead-payment/'

spring:
  application:
    name: ead-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-payment
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://takilztr:DNmWXGQ5t2lPE5wF3F-UmmV_8Oz0fFAs@leopard.lmq.cloudamqp.com/takilztr
  
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      userEventExchange: ead.userevent
      paymentCommandExchange: ead.paymentcommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.payment
      paymentCommandQueue:
        name: ead.paymentcommand.ms.payment
    key:
      paymentCommandoKey: ms.payment
  stripe:
    secretKey: '(cipher)92ffabbd8cbaae6bcecb51396f3ed7dba1f80a4be95767e19316652ec0579e3bd1ebe656b49b01879df352ae15eee5d6051c945d2545f48c79b37733c6e27a995ab157690ca74bd20ee041f8c1dc36720525f96883a7f5f758ca8e6d49640e7e6ff532116190970bb1b1c68ca04fc66e21be275640bf6883d6ff6c1e27c74b56'

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
