server:
  port: 8086
  servlet:
    context-path: '/ead-payment/'

spring:
  application:
    name: ead-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-payment
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://takilztr:DNmWXGQ5t2lPE5wF3F-UmmV_8Oz0fFAs@leopard.lmq.cloudamqp.com/takilztr
  
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      userEventExchange: ead.userevent
      paymentCommandExchange: ead.paymentcommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.payment
      paymentCommandQueue:
        name: ead.paymentcommand.ms.payment
    key:
      paymentCommandKey: ms.payment
  stripe:
    secretKey: '{cipher}10ed84f7511d39763028251f0cb42abed1ab33467bd5210c3e8e49ff807339771271209fc5a4abc1bc87da6d118310753ef2ed28deee5b735b7005f70126ef2658c1d5794c2178b2159f39d306a71682e0a58e8303fcbbc8f4ddd70b10919e40f33a32d463e9878d1a4b29294b525362c424a5fa3967712d74085783218a1d06'

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
