server:
  port: 8086
  servlet:
    context-path: '/ead-payment/'

spring:
  application:
    name: ead-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-payment
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://takilztr:DNmWXGQ5t2lPE5wF3F-UmmV_8Oz0fFAs@leopard.lmq.cloudamqp.com/takilztr
  
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      userEventExchange: ead.userevent
      paymentCommandExchange: ead.paymentcommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.payment
      paymentCommandQueue:
        name: ead.paymentcommand.ms.payment
    key:
      paymentCommandKey: ms.payment
  stripe:
    secretKey: '(cipher)b181a905be405ad3f3f9cd6c546cb271782f2dbbead5f94b09dcadb665d5e1522127eb859a2ebe8bf805df1144ab6a6d3a23fefc65dc824d9ccd41ca2ccd4c3f9420dd6765bda9c010ff32270c2d1f9e055ffd40c326f8cf5b1d6fe4284cc3b3e5a621a0f487102c7591c7a23f1a49dd4e18d1beb6883e588effeca39439428e'

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
